version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  commit-message:
    prefix: "npm"
  labels: [ 'chore' ]
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
  groups:
    npm-prod-dependencies:
      applies-to: version-updates
      dependency-type: "production"
    npm-dev-dependencies:
      dependency-type: "development"
      applies-to: version-updates
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "actions"
  labels: [ 'chore' ]
  reviewers:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    actions-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
